### ISSUE TITLE
The xz backdoor situation

### ISSUE THREAD

**Issue by midchildan** [midchildan/dotfiles#127]
## Problem
The upstream tarball of xz was found to be backdoored. Fortunately, it reportedly doesn't affect the Nixpkgs package because the backdoor is only inserted into the binary on DEB and RPM based build environments. However, the user behind the backdoor has other commits in multiple high profile open source projects which haven't been further scrutinized yet.

## TODO
* [x] ~Temporarily downgrade Nixpkgs to a commit that doesn't include the compromised version of xz?~
* [x] Apply https://github.com/NixOS/nixpkgs/pull/300028 ([Progress](https://nixpk.gs/pr-tracker.html?pr=300028))
* [x] ~Apply https://github.com/NixOS/nixpkgs/pull/300122 ([Progress](https://nixpk.gs/pr-tracker.html?pr=300122))~
* [x] Apply https://github.com/NixOS/nixpkgs/pull/300114 ([Progress](https://nixpk.gs/pr-tracker.html?pr=300114))

## References
* https://www.openwall.com/lists/oss-security/2024/03/29/
* https://discourse.nixos.org/t/cve-2024-3094-malicious-code-in-xz-5-6-0-and-5-6-1-tarballs/42405/31
* https://gist.github.com/thesamesam/223949d5a074ebc3dce9ee78baad9e27
* https://boehs.org/node/everything-i-know-about-the-xz-backdoor
* https://news.ycombinator.com/item?id=39865810

**Comment by midchildan** [comment]
introduced: 7a14d4e6c8e5090b4d6a57d655ca87af4b60d6e0
fixed: 1e266af2115f312899c5ce329a4215a1afbdcafb
